#secret is a file used to store credentials in encryption form .
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: 
    mongo-root-username: dXNlcm5hbWU=  #echo -n 'username' | base64 --> it is the command to convert plain txt into base64 encryption.
    mongo-root-password: cGFzc3dvcmQ=
      
